### ISSUE TITLE
Wrong login credentials result in 500 Error

### ISSUE THREAD

**Issue by OpentheChampagne** [felipecast/getstrongwithme#1]
When attempting to login with the wrong login information, the site returns a 500 error.

**Comment by OpentheChampagne** [comment]
Heroku logs: 
2021-02-24T05:53:42.013275+00:00 app[web.1]: [2021-02-24 05:53:42,012] ERROR in app: Exception on /login [POST]
2021-02-24T05:53:42.013278+00:00 app[web.1]: Traceback (most recent call last):
2021-02-24T05:53:42.013279+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
2021-02-24T05:53:42.013280+00:00 app[web.1]:     response = self.full_dispatch_request()
2021-02-24T05:53:42.013281+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
2021-02-24T05:53:42.013282+00:00 app[web.1]:     rv = self.handle_user_exception(e)
2021-02-24T05:53:42.013282+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
2021-02-24T05:53:42.013282+00:00 app[web.1]:     reraise(exc_type, exc_value, tb)
2021-02-24T05:53:42.013283+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
2021-02-24T05:53:42.013284+00:00 app[web.1]:     raise value
2021-02-24T05:53:42.013285+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
2021-02-24T05:53:42.013285+00:00 app[web.1]:     rv = self.dispatch_request()
2021-02-24T05:53:42.013286+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
2021-02-24T05:53:42.013286+00:00 app[web.1]:     return self.view_functions[rule.endpoint](**req.view_args)
2021-02-24T05:53:42.013287+00:00 app[web.1]:   File "/app/main.py", line 83, in login_
2021-02-24T05:53:42.013287+00:00 app[web.1]:     if user.check_password(request.form["password"]):
2021-02-24T05:53:42.013418+00:00 app[web.1]: AttributeError: 'NoneType' object has no attribute 'check_password'
2021-02-24T05:53:42.015828+00:00 app[web.1]: 10.101.178.182 - - [24/Feb/2021:05:53:42 +0000] "POST /login HTTP/1.1" 500 290 "http://getstrongwith.me/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.3 Safari/605.1.15"
