### ISSUE TITLE
Searching results in a 500

### ISSUE THREAD

**Issue by OpentheChampagne** [felipecast/getstrongwithme#6]
Searching for anything results in a 500 error. 

Heroku Error Log: 

2021-02-24T05:32:03.406059+00:00 heroku[router]: at=info method=POST path="/search" host=getstrongwith.me request_id=7f680482-1073-4873-b995-ac10ea15a3f9 fwd="69.136.108.58" dyno=web.1 connect=1ms service=18ms status=500 bytes=470 protocol=http
2021-02-24T05:32:03.402603+00:00 app[web.1]: [2021-02-24 05:32:03,401] ERROR in app: Exception on /search [POST]
2021-02-24T05:32:03.402631+00:00 app[web.1]: Traceback (most recent call last):
2021-02-24T05:32:03.402633+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
2021-02-24T05:32:03.402633+00:00 app[web.1]:     response = self.full_dispatch_request()
2021-02-24T05:32:03.402646+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
2021-02-24T05:32:03.402647+00:00 app[web.1]:     rv = self.handle_user_exception(e)
2021-02-24T05:32:03.402647+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
2021-02-24T05:32:03.402647+00:00 app[web.1]:     reraise(exc_type, exc_value, tb)
2021-02-24T05:32:03.402648+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
2021-02-24T05:32:03.402648+00:00 app[web.1]:     raise value
2021-02-24T05:32:03.402649+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
2021-02-24T05:32:03.402649+00:00 app[web.1]:     rv = self.dispatch_request()
2021-02-24T05:32:03.402649+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
2021-02-24T05:32:03.402651+00:00 app[web.1]:     return self.view_functions[rule.endpoint](**req.view_args)
2021-02-24T05:32:03.402651+00:00 app[web.1]:   File "/app/main.py", line 159, in search_
2021-02-24T05:32:03.402652+00:00 app[web.1]:     return render_template("search.html", search=User.query.filter(User.firstName.like(query)))
2021-02-24T05:32:03.402894+00:00 app[web.1]: NameError: name 'query' is not defined
2021-02-24T05:32:03.404750+00:00 app[web.1]: 10.47.238.174 - - [24/Feb/2021:05:32:03 +0000] "POST /search HTTP/1.1" 500 290 "http://getstrongwith.me/home" "Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.192 Safari/537.36"

**Comment by zscrub** [comment]
500 error worked around,  /search still in progress
